/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChangePasswordDialog: typeof import('./src/components/profile/ChangePasswordDialog.vue')['default']
    CheckIcon: typeof import('./src/components/icons/CheckIcon.vue')['default']
    CloseIcon: typeof import('./src/components/icons/CloseIcon.vue')['default']
    CodeExampleSelector: typeof import('./src/components/code/CodeExampleSelector.vue')['default']
    CommentItem: typeof import('./src/components/article/CommentItem.vue')['default']
    DanmakuMessage: typeof import('./src/components/chat/DanmakuMessage.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElStatistic: typeof import('element-plus/es')['ElStatistic']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ErrorIcon: typeof import('./src/components/icons/ErrorIcon.vue')['default']
    EyeIcon: typeof import('./src/components/icons/EyeIcon.vue')['default']
    EyeOffIcon: typeof import('./src/components/icons/EyeOffIcon.vue')['default']
    ForgotPasswordDialog: typeof import('./src/components/auth/ForgotPasswordDialog.vue')['default']
    InfoIcon: typeof import('./src/components/icons/InfoIcon.vue')['default']
    LanguageSelector: typeof import('./src/components/code/LanguageSelector.vue')['default']
    LoginForm: typeof import('./src/components/auth/LoginForm.vue')['default']
    MonacoEditor: typeof import('./src/components/code/MonacoEditor.vue')['default']
    NewsCarousel: typeof import('./src/components/news/NewsCarousel.vue')['default']
    OutputPanel: typeof import('./src/components/code/OutputPanel.vue')['default']
    PerformanceMonitor: typeof import('./src/components/shared/PerformanceMonitor.vue')['default']
    RegisterForm: typeof import('./src/components/auth/RegisterForm.vue')['default']
    ResourceCommentItem: typeof import('./src/components/resource/ResourceCommentItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkeletonLoader: typeof import('./src/components/shared/SkeletonLoader.vue')['default']
    StatsSkeleton: typeof import('./src/components/shared/StatsSkeleton.vue')['default']
    UserIcon: typeof import('./src/components/icons/UserIcon.vue')['default']
    WarningIcon: typeof import('./src/components/icons/WarningIcon.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
