/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CheckIcon: typeof import('./src/components/icons/CheckIcon.vue')['default']
    CloseIcon: typeof import('./src/components/icons/CloseIcon.vue')['default']
    ErrorIcon: typeof import('./src/components/icons/ErrorIcon.vue')['default']
    EyeIcon: typeof import('./src/components/icons/EyeIcon.vue')['default']
    EyeOffIcon: typeof import('./src/components/icons/EyeOffIcon.vue')['default']
    InfoIcon: typeof import('./src/components/icons/InfoIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserIcon: typeof import('./src/components/icons/UserIcon.vue')['default']
    WarningIcon: typeof import('./src/components/icons/WarningIcon.vue')['default']
  }
}
