name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: my-vue-app
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: my-vue-app/package-lock.json
      - run: npm ci
      - run: npm run type-check
      - run: npm run lint:check
      - run: npm run build
